######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 24 04:35:28 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += IHM.ui
SOURCES += main.cpp mainwindow.cpp
